#pragma once

namespace godot {

typedef enum {
	COL_LAYER_WORLD = 1 << 0,
	COL_LAYER_PLAYER = 1 << 1,
	COL_LAYER_PROPS = 1 << 2,
	COL_LAYER_ENEMIES = 1 << 3,
	COL_LAYER_STICKY_GRENADE = 1 << 4,
	COL_LAYER_GIBS = 1 << 5,
	COL_LAYER_LOSBLOCK = 1 << 6,
} CollisionLayers;

typedef enum {
	COL_MASK_WORLD = 0,
	COL_MASK_PLAYER = COL_LAYER_WORLD | COL_LAYER_ENEMIES | COL_LAYER_PROPS,
	COL_MASK_PROPS = COL_LAYER_WORLD | COL_LAYER_PLAYER | COL_LAYER_PROPS | COL_LAYER_ENEMIES,
	COL_MASK_ENEMIES = COL_LAYER_WORLD | COL_LAYER_PLAYER,
	COL_MASK_PLAYERPROJECTILE = COL_LAYER_WORLD | COL_LAYER_PROPS | COL_LAYER_ENEMIES,
	COL_MASK_STICKY_EXPLOSION = COL_LAYER_PLAYER | COL_LAYER_PROPS | COL_LAYER_ENEMIES | COL_LAYER_STICKY_GRENADE,
	COL_MASK_CAMERA = COL_LAYER_WORLD,
	COL_MASK_GIBS = COL_LAYER_WORLD | COL_LAYER_PLAYER | COL_LAYER_PROPS | COL_LAYER_ENEMIES,
	COL_MASK_ENEMY_PROJECTILE = COL_LAYER_WORLD | COL_LAYER_PLAYER | COL_LAYER_PROPS | COL_LAYER_ENEMIES,
	COL_MASK_LOS = COL_LAYER_WORLD | COL_LAYER_PROPS | COL_LAYER_ENEMIES | COL_LAYER_LOSBLOCK,
	COL_MASK_ITEMS = COL_LAYER_PLAYER,
} CollisionMasks;

}