#pragma once

#include <godot_cpp/variant/aabb.hpp>
#include <godot_cpp/variant/color.hpp>

namespace godot {

typedef enum {
	COL_LAYER_NONE = 0,
	COL_LAYER_WORLD = 1 << 0,
	COL_LAYER_PLAYER = 1 << 1,
	COL_LAYER_PROPS = 1 << 2,
	COL_LAYER_ENEMIES = 1 << 3,
	COL_LAYER_STICKY_GRENADE = 1 << 4,
	COL_LAYER_GIBS = 1 << 5,
	COL_LAYER_LOSBLOCK = 1 << 6,
} CollisionLayers;

typedef enum {
	COL_MASK_WORLD = 0,
	COL_MASK_PLAYER = COL_LAYER_WORLD | COL_LAYER_ENEMIES | COL_LAYER_PROPS,
	COL_MASK_PROPS = COL_LAYER_WORLD | COL_LAYER_PLAYER | COL_LAYER_PROPS | COL_LAYER_ENEMIES,
	COL_MASK_ENEMIES = COL_LAYER_WORLD | COL_LAYER_PLAYER,
	COL_MASK_PLAYER_PROJECTILE = COL_LAYER_WORLD | COL_LAYER_PROPS | COL_LAYER_ENEMIES,
	COL_MASK_ENEMY_PROJECTILE = COL_LAYER_WORLD | COL_LAYER_PLAYER | COL_LAYER_PROPS,
	COL_MASK_STICKY_EXPLOSION = COL_LAYER_PLAYER | COL_LAYER_PROPS | COL_LAYER_ENEMIES | COL_LAYER_STICKY_GRENADE,
	COL_MASK_CAMERA = COL_LAYER_WORLD,
	COL_MASK_GIBS = COL_LAYER_WORLD | COL_LAYER_PLAYER | COL_LAYER_PROPS | COL_LAYER_ENEMIES,
	COL_MASK_LOS = COL_LAYER_WORLD | COL_LAYER_PROPS | COL_LAYER_ENEMIES | COL_LAYER_LOSBLOCK,
	COL_MASK_ITEMS = COL_LAYER_PLAYER,
} CollisionMasks;

const AABB DEFAULT_STAGE_BOUNDS = AABB(
		Vector3(-512, -64, -512),
		Vector3(1024, 512, 1024));

const Color COLOR_DEBUG_COLL = Color(0., 1., 0.);
const Color COLOR_DEBUG_ERROR = Color(1., 0., 1.);

} //namespace godot
